create table if not exists public.users (
  id integer generated by default as identity primary key,
  email varchar(255) not null,
  display_name varchar(120) not null,
  hashed_password varchar not null,
  total_points integer not null default 0
);

create unique index if not exists ix_users_email
  on public.users (email);

create index if not exists ix_users_id
  on public.users (id);

create table if not exists public.module_progress (
  id integer generated by default as identity primary key,
  module_slug varchar(100) not null,
  best_score integer not null default 0,
  attempts integer not null default 0,
  completed boolean not null default false,
  earned_points integer not null default 0,
  user_id integer not null references public.users (id)
);

create index if not exists ix_module_progress_id
  on public.module_progress (id);

create index if not exists ix_module_progress_module_slug
  on public.module_progress (module_slug);
